In [ ]:
1. What is a Python library? Why ^o we use Python libraries?

A Python library is a collection of pre-written and reusable code modules that provide specific functionality. These libraries are designed to help developers perform common tasks without having to implement the code from scratch. Here’s why we use Python libraries:

Reusability: Libraries encapsulate code that can be reused across different projects and by different developers, saving time and effort.

Functionality: They provide ready-made functions and classes to perform specific operations or solve particular problems, which helps in implementing complex tasks quickly.

Efficiency: Using libraries often results in more efficient code, as they are usually well-tested and optimized for performance.

Community and Support: Python libraries are often developed and maintained by a community of developers, ensuring ongoing support, bug fixes, and updates.

Integration: Libraries allow easy integration with other components of a system, such as databases, web frameworks, or APIs.

Standards: Many Python libraries adhere to coding standards and best practices, ensuring reliability and consistency in development.

In [ ]:
2. What is the difference between Numpy array and List?

Data Type and Homogeneity:
NumPy Array: NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type (e.g., integers, floats). This allows for efficient storage and operations.
List: Python lists can contain elements of different data types and can even store other lists or complex objects within them.

Performance:
NumPy Array: NumPy arrays are more efficient for numerical operations than lists. This efficiency is primarily due to their homogeneity and contiguous memory allocation, which allows NumPy to leverage optimized, pre-compiled C-code for operations.
List: Lists are more flexible but are slower for numerical computations because they are not optimized for such operations.

Size Dynamism:
NumPy Array: The size of a NumPy array is fixed when it is created. Changing the size of an array will create a new array and delete the original.
List: Lists in Python are dynamic and can grow or shrink as needed by appending or removing elements. This dynamic resizing can lead to overhead and slower performance compared to NumPy arrays.

Functionality and Methods:
NumPy Array: NumPy arrays offer a wide variety of mathematical operations and functions that can be performed directly on the entire array without the need for explicit loops.
List: Lists have a smaller set of built-in methods compared to NumPy arrays, and for numerical operations, you often need to iterate through the list, which can be slower.

Usage:
NumPy Array: NumPy arrays are commonly used in scientific computing, data analysis, machine learning, and tasks involving large datasets where performance is critical.
List: Lists are used in general-purpose programming for storing collections of arbitrary objects and are suitable for tasks where flexibility and ease of use are more important than performance.

In [ ]:
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
import numpy as np

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Dimension :",arr1.ndim)
print("Size :",arr1.size)
print("Shape :",arr1.shape)

Dimension : 2
Size : 12
Shape : (3, 4)


In [ ]:
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
arr1[0]

array([1, 2, 3, 4])

In [ ]:
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [17]:
print(arr1[2,:])
print(arr1[:,3])

[ 9 10 11 12]
[ 4  8 12]


In [ ]:
6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [18]:
arr1[arr1 % 2 ==1]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [23]:
arr2 = np.random.randint(0,2,size=(3,3))
arr2

array([[1, 1, 1],
       [1, 1, 0],
       [1, 0, 1]])

In [ ]:
8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand:

Distribution: Generates random numbers from a uniform distribution over the interval 
[0,1).
Shape: Accepts dimensions as separate arguments (not as a tuple).
Usage: Typically used when you need random numbers that are uniformly distributed between 0 and 1.


np.random.randn:

Distribution: Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
Shape: Accepts dimensions as a tuple.
Usage: Used when you need random numbers that follow a normal (Gaussian) distribution

In [ ]:
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [28]:
print("Original Dimension :",arr1.ndim)
arr2=np.expand_dims(arr1,axis=0)
print("Expanded dimention :",arr2.ndim)

Original Dimension : 2
Expanded dimention : 3


In [ ]:
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1 Index wiLe multiplication
2 Matix multiplicatio'
3 Add both the maticK
4 Subtact matix B om 
5 Divide Matix B by A

In [34]:
# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Add both matrices
addition_result = A2 + B2
print("Addition result:")
print(addition_result)

# Subtract matrix B from matrix A
subtraction_result = A2 - B2
print("\nSubtraction result (A2 - B2):")
print(subtraction_result)

# Matrix multiplication
multiplication_result = np.multiply(A2,B2)  # Assuming you want to perform matrix multiplication
print("\nMatrix multiplication result:")
print(multiplication_result)

# Element-wise division of matrix B by matrix A
division_result = np.divide(B2, A2)
print("\nDivision result (B2 / A2):")
print(division_result)


Addition result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction result (A2 - B2):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix multiplication result:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Division result (B2 / A2):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
12. Which function in Numpy can be used to swap the byte order of an array?

In [35]:
arr = np.array([1, 256], dtype=np.int16)
print("Original array:")
print(arr)

# Swap the byte order of the array
arr.byteswap(True)
print("\nArray after byte swapping:")
print(arr)

Original array:
[  1 256]

Array after byte swapping:
[256   1]


In [ ]:
13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function is used to compute the multiplicative inverse of a matrix. It is significant in linear algebra and is commonly used in various mathematical computations, including solving systems of linear equations and computing determinants.

In [38]:
A = np.array([[2, 1], [1, 3]])
print("Original matrix:")
print(A)

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)
print("\nInverse of the matrix:")
print(A_inv)

Original matrix:
[[2 1]
 [1 3]]

Inverse of the matrix:
[[ 0.6 -0.2]
 [-0.2  0.4]]


In [ ]:
14. What does the np.reshape function do, and how is it used?

The np.reshape function is used to change the shape of an array without changing its data. It returns a new array with a modified shape. This function is useful for reorganizing data to fit different dimensional requirements.

In [39]:
arr = np.arange(12)
print("Original 1D array:")
print(arr)

# Reshape the array into a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))
print("\nReshaped 3x4 matrix:")
print(reshaped_arr)

Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
15. What is broadcasting in Numpy?

Broadcasting is a mechanism in NumPy that allows arrays with different shapes to be combined in arithmetic operations. When performing operations on arrays with different shapes, NumPy automatically "broadcasts" the arrays to make their shapes compatible, effectively extending the smaller array to match the shape of the larger one. This allows element-wise operations to be performed between arrays of different shapes without explicitly reshaping them. Broadcasting is an essential feature in NumPy that simplifies many array computations and makes code more concise and readable.